# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulator_obuchni.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 491)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reverse = QtWidgets.QPushButton(self.centralwidget)
        self.reverse.setGeometry(QtCore.QRect(10, 400, 71, 51))
        self.reverse.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.reverse.setObjectName("reverse")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(80, 400, 71, 51))
        self.zero.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.zero.setObjectName("zero")
        self.zapetai = QtWidgets.QPushButton(self.centralwidget)
        self.zapetai.setGeometry(QtCore.QRect(150, 400, 71, 51))
        self.zapetai.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.zapetai.setObjectName("zapetai")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(10, 350, 71, 51))
        self.one.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(80, 350, 71, 51))
        self.two.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(150, 350, 71, 51))
        self.three.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.three.setObjectName("three")
        self.sixe = QtWidgets.QPushButton(self.centralwidget)
        self.sixe.setGeometry(QtCore.QRect(150, 300, 71, 51))
        self.sixe.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.sixe.setObjectName("sixe")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(80, 300, 71, 51))
        self.five.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.five.setObjectName("five")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(10, 300, 71, 51))
        self.four.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.four.setObjectName("four")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(80, 250, 71, 51))
        self.eight.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(150, 250, 71, 51))
        self.nine.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.nine.setObjectName("nine")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 250, 71, 51))
        self.seven.setStyleSheet("background-color: rgb(30, 30, 36);\n"
"color: rgb(255, 255, 255);")
        self.seven.setObjectName("seven")
        self.otvet = QtWidgets.QPushButton(self.centralwidget)
        self.otvet.setGeometry(QtCore.QRect(220, 400, 71, 51))
        self.otvet.setStyleSheet("background-color: rgb(229, 75, 75);\n"
"color: rgb(255, 255, 255);")
        self.otvet.setObjectName("otvet")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(220, 300, 71, 51))
        self.minus.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.minus.setObjectName("minus")
        self.umnohit = QtWidgets.QPushButton(self.centralwidget)
        self.umnohit.setGeometry(QtCore.QRect(220, 250, 71, 51))
        self.umnohit.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.umnohit.setObjectName("umnohit")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(220, 350, 71, 51))
        self.plus.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.plus.setObjectName("plus")
        self.podelit = QtWidgets.QPushButton(self.centralwidget)
        self.podelit.setGeometry(QtCore.QRect(220, 200, 71, 51))
        self.podelit.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.podelit.setObjectName("podelit")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(220, 150, 71, 51))
        self.delete_2.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.delete_2.setObjectName("delete_2")
        self.delete_all = QtWidgets.QPushButton(self.centralwidget)
        self.delete_all.setGeometry(QtCore.QRect(150, 150, 71, 51))
        self.delete_all.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.delete_all.setObjectName("delete_all")
        self.new_number = QtWidgets.QLabel(self.centralwidget)
        self.new_number.setGeometry(QtCore.QRect(20, 100, 271, 51))
        self.new_number.setStyleSheet("")
        self.new_number.setObjectName("new_number")
        self.old_number = QtWidgets.QLabel(self.centralwidget)
        self.old_number.setGeometry(QtCore.QRect(20, 40, 271, 51))
        self.old_number.setStyleSheet("")
        self.old_number.setText("")
        self.old_number.setObjectName("old_number")
        self.stepen = QtWidgets.QPushButton(self.centralwidget)
        self.stepen.setGeometry(QtCore.QRect(80, 200, 71, 51))
        self.stepen.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.stepen.setObjectName("stepen")
        self.koren = QtWidgets.QPushButton(self.centralwidget)
        self.koren.setGeometry(QtCore.QRect(150, 200, 71, 51))
        self.koren.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.koren.setObjectName("koren")
        self.faktorial = QtWidgets.QPushButton(self.centralwidget)
        self.faktorial.setGeometry(QtCore.QRect(10, 200, 71, 51))
        self.faktorial.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.faktorial.setObjectName("faktorial")
        self.pi = QtWidgets.QPushButton(self.centralwidget)
        self.pi.setGeometry(QtCore.QRect(80, 150, 71, 51))
        self.pi.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.pi.setObjectName("pi")
        self.ee = QtWidgets.QPushButton(self.centralwidget)
        self.ee.setGeometry(QtCore.QRect(10, 150, 71, 51))
        self.ee.setStyleSheet("background-color: rgb(68, 65, 64);\n"
"color: rgb(255, 255, 255);")
        self.ee.setObjectName("ee")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reverse.setText(_translate("MainWindow", "+/-"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.zapetai.setText(_translate("MainWindow", ","))
        self.one.setText(_translate("MainWindow", "1"))
        self.two.setText(_translate("MainWindow", "2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.sixe.setText(_translate("MainWindow", "6"))
        self.five.setText(_translate("MainWindow", "5"))
        self.four.setText(_translate("MainWindow", "4"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.otvet.setText(_translate("MainWindow", "="))
        self.minus.setText(_translate("MainWindow", "-"))
        self.umnohit.setText(_translate("MainWindow", "x"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.podelit.setText(_translate("MainWindow", "/"))
        self.delete_2.setText(_translate("MainWindow", "<"))
        self.delete_all.setText(_translate("MainWindow", "C"))
        self.new_number.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.new_number.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.new_number.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p><p align=\"right\"><br/></p></body></html>"))
        self.stepen.setText(_translate("MainWindow", "x^y"))
        self.koren.setText(_translate("MainWindow", "2√x"))
        self.faktorial.setText(_translate("MainWindow", "!"))
        self.pi.setText(_translate("MainWindow", "pi"))
        self.ee.setText(_translate("MainWindow", "e"))
